# Logging and Output arguments
log_level: info
logging_strategy: steps
logging_steps: 100
report_to:
- tensorboard
- wandb
save_strategy: "no"
output_dir: data/vit-medical
overwrite_output_dir: true


# Model arguments
model_config:
  hidden_size: 512
  intermediate_size: 2048
  num_hidden_layers: 16
  hidden_act: "silu"
  max_position_embeddings: 2048
  num_attention_heads: 4
  image_size: 480
  patch_size: 16
  num_channels: 3


model_name_or_path: google/vit-base-patch16-224-in21k
torch_dtype: bfloat16

# Data training arguments
dataset_name: ./split_datasets
remove_unused_columns: false
dataset_configs:
- all
preprocessing_num_workers: 1

# PT trainer arguments
seed: 233
do_train: True
max_train_steps: 8000
per_device_train_batch_size: 1
do_eval: True
eval_strategy: steps
eval_steps: 100
per_device_eval_batch_size: 1
optim: adamw_torch_fused
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
learning_rate: 8.0e-3
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
  warmup_type: linear
  decay_type: linear
  num_decay_steps: 800
  min_lr_ratio: 0.0
warmup_steps: 800
weight_decay: 0.01
gradient_accumulation_steps: 256
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
max_grad_norm: 1.0
bf16: True
